---
output: hugodown::hugo_document

slug: three-new-tidymodels-packages
title: "Three New tidymodels Packages"
date: 2025-09-03
author: Max Kuhn, Frances Lin, Simon Couch
description: >
    A 2-3 sentence description of the post that appears on the articles page.
    This can be omitted if it would just recapitulate the title.

photo:
  url: https://unsplash.com/photos/three-french-macaroons-on-plate-71jYZb6Ag7M
  author: Keila Hötzel

# one of: "deep-dive", "learn", "package", "programming", "roundup", or "other"
categories: [package] 
tags: [tidymodels,postprocessing,feature-selection]
---

<!--
TODO:
* [ ] Look over / edit the post's title in the yaml
* [ ] Edit (or delete) the description; note this appears in the Twitter card
* [ ] Pick category and tags (see existing with `hugodown::tidy_show_meta()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::use_tidy_thumbnails()`
* [ ] Add intro sentence, e.g. the standard tagline for the package
* [ ] `usethis::use_tidy_thanks()`
-->

We're very chuffed to announce the release of _three_ new modeling packages: filtro, important, and tailor. 

You can install them from CRAN with:

```{r, eval = FALSE}
install.packages(c("filtro", "important", "tailor"))
```

This blog post will describe each. 

## filtro

Feature selection is one of the most important steps in building robust machine learning models. By keeping only the most relevant predictors, we can reduce overfitting, improve model interpretability, and speed up computation.

filtro is tidy tools designed specifically for filter-based supervised feature selection.

filtro makes it easy to score, rank, and select features using a wide range of statistical and model-based metrics. These include:

- p-values

- correlation

- random forest feature importance

- information gain, and more.

With filtro, you can quickly rank your variables and select either the top proportion or the top number features that best contribute to your model.

Sometimes, you may want to combine multiple scores into one unified score. filtro also supports multiparameter optimization, powered by the desirability2 package.

## important

## tailor

## Acknowledgements

